---
title: "Injury Analysis Outline"
author: "Carmen Canedo"
date: "29 November 2020"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Outline

  1. Discuss Hypothesis
  
    + Participation in sports is decreasing due to sports-related injuries
    
  2. Injuries
  
    + How many kids are getting hurt?
    
      + Youth Emergency Visits for Brain Injuries (Bar chart)
      
    + What are the demographics of the people getting hurt?
    
      + Number of Concussions by Gender (Paired bar chart)
      
    + What sports have the most injuries?
    
      + Boxplots of mean median modes by sport
      
    + How have injuries rates changed over time?
    
      + Line Charts by Sport
      
  3. Participation
  
    + Who participates in sports?
    
      + Choropleth map of participation
      
      + Bar chart of participation by gender
      
    + How many people participate in sports?
    
      + Line graph of participation by sport
      
  4. Conclusion
  
    + Viz comparing injuries by participation over time
    
    + Survey Responses on The Long-Term Effects of Concussions in Sport (Stacked Bar chart)
    


