---
title: "Superbowl Viewership vs Worker Productivity"
author: "Joseph Bernardi"
date: "10/12/2020"
output: word_document
---

### Goal

This exploration seeks to identify the correlation between Superbowl Viewership and US Worker Productivity. The idea behind this common hypothesis is that as working class people devote more hours per day to their jobs, the less likely that they will watch sporting events such as the Superbowl.

### Methods and Data

In order to quantify worker productivity data, I will be using "Real Output Per Hour of All Persons" from the Federal Reserve Bank of St. Louis' Economic Research data, more specifically, in the nonfarm sector (meaning farming is not included). I will also be using the total yearly viewership of the Superbowl. Both inputs will are represented as percent change via Microsoft Excel.

### Visualization

```{r echo=FALSE}

library(tidyverse)
library(ggplot2)

proddata <- read.csv("data/productivity-data/prod_vs_viewing.csv")

df <- as_tibble(proddata)

ggplot(df, aes(ï..Year)) + 
  geom_line(aes(y = pctchangeSuperBowl, colour = "pctchangeSuperBowl")) + 
  geom_line(aes(y = pctchangeWorkerProd, colour = "pctchangeWorkerProd"))


  
```


### Interpretations and Conclusions

There are not necessarily any major interpretations regarding the correlation between worker productivity and Superbowl viewership from this visualization. One observation is that when worker productivity began to dip around 2017, Superbowl viewership did rise to an extent. However, at the beginning of the time frame, there seemed to be a positive correlation between the two inputs. To conclude, one can observe that there does not seem to be any consistent correlation between these two inputs.